services:

  test-redis:
    image: 'cimg/redis:6.2'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'

  test-wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    ports:
      - "9091:8080"
    command: '--verbose'

networks:
  hmpps_int:
