import fs from 'fs/promises'
import path from 'path'
import Component from './component'

export default class Writer {
  private static async componentDirectoryPaths(): Promise<string[]> {
    const componentsPath = 'node_modules/govuk-frontend/govuk/components'
    const componentsDirectoryContents = await fs.readdir(componentsPath)

    const componentsDirectoryContentsStats = await Promise.all(
      componentsDirectoryContents
        .map(item => path.join(componentsPath, item))
        .map(async componentPath => ({ componentPath, stat: await fs.lstat(componentPath) }))
    )

    // There's an _all.scss file lurking in there which we want to exclude
    return componentsDirectoryContentsStats.filter(item => item.stat.isDirectory()).map(item => item.componentPath)
  }

  private static async components(): Promise<Component[]> {
    const componentDirectoryPaths = await this.componentDirectoryPaths()

    return Promise.all(
      componentDirectoryPaths.map(async directoryPath => {
        const macroOptionsBuffer = await fs.readFile(path.join(directoryPath, 'macro-options.json'))
        const macroOptions = JSON.parse(macroOptionsBuffer.toString())

        return new Component(path.basename(directoryPath), macroOptions)
      })
    )
  }

  static async writeDefinitions(): Promise<void> {
    const components = await this.components()

    const output = `// THIS FILE IS AUTOMATICALLY GENERATED. DON’T MODIFY IT MANUALLY.
// Re-generate this file by running \`npm run-script generate-frontend-types\`.

${components.map(component => component.definitions).join('\n')}
`

    const outputPath = 'server/utils/govukFrontendTypes.ts'
    await fs.writeFile(outputPath, output)
  }
}
