replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-interventions-ui
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  host: hmpps-interventions-ui-research.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  COMMUNITY_API_URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
  OFFENDER_ASSESSMENTS_API_URL: http://offender-dev.aks-dev-1.studio-hosting.service.justice.gov.uk/
  INTERVENTIONS_SERVICE_URL: https://hmpps-interventions-service-research.apps.live-1.cloud-platform.service.justice.gov.uk
  TOKEN_VERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
  TOKEN_VERIFICATION_ENABLED: true
  REDIS_TLS_ENABLED: true
