insert into pcc_region (id, name, nps_region_id) values
    ('avon-and-somerset','Avon & Somerset','G'),
    ('bedfordshire','Bedfordshire','I'),
    ('cambridgeshire','Cambridgeshire','I'),
    ('cheshire','Cheshire','B'),
    ('city-of-london','City of London','J'),
    ('cleveland','Cleveland','A'),
    ('cumbria','Cumbria','B'),
    ('derbyshire','Derbyshire','F'),
    ('devon-and-cornwall','Devon & Cornwall','G'),
    ('dorset','Dorset','G'),
    ('durham','Durham','A'),
    ('dyfed-powys','Dyfed-Powys','D'),
    ('essex','Essex','I'),
    ('gloucestershire','Gloucestershire','G'),
    ('gwent','Gwent','D'),
    ('hampshire','Hampshire','H'),
    ('hertfordshire','Hertfordshire','I'),
    ('humberside','Humberside','C'),
    ('kent','Kent','K'),
    ('lancashire','Lancashire','B'),
    ('leicestershire','Leicestershire','F'),
    ('lincolnshire','Lincolnshire','F'),
    ('merseyside','Merseyside','B'),
    ('norfolk','Norfolk','I'),
    ('north-wales','North Wales','D'),
    ('north-yorkshire','North Yorkshire','C'),
    ('northamptonshire','Northamptonshire','I'),
    ('northumbria','Northumbria','A'),
    ('nottinghamshire','Nottinghamshire','F'),
    ('south-wales','South Wales','D'),
    ('south-yorkshire','South Yorkshire','C'),
    ('staffordshire','Staffordshire','E'),
    ('suffolk','Suffolk','I'),
    ('surrey','Surrey','K'),
    ('sussex','Sussex','K'),
    ('thames-valley','Thames Valley','H'),
    ('warwickshire','Warwickshire','E'),
    ('west-mercia','West Mercia','E'),
    ('west-midlands','West Midlands','E'),
    ('west-yorkshire','West Yorkshire','C'),
    ('wiltshire','Wiltshire','G');
