insert into complexity_level (id, service_category_id, title, description)
    values
        -- Accommodation Service Category:
        ('d0db50b0-4a50-4fc7-a006-9c97530e38b2', '428ee70f-3001-4399-95a6-ad25eaaede16', 'Low complexity', 'Service User has some capacity and means to secure and/or maintain suitable accommodation but requires some support and guidance to do so.'),
        ('110f2405-d944-4c15-836c-0c6684e2aa78', '428ee70f-3001-4399-95a6-ad25eaaede16', 'Medium complexity', 'Service User is at risk of homelessness/is homeless, or will be on release from prison. Service User has had some success in maintaining atenancy but may have additional needs e.g. Learning Difficulties and/or Learning Disabilities or other challenges currently.'),
        ('c86be5ec-31fa-4dfa-8c0c-8fe13451b9f6', '428ee70f-3001-4399-95a6-ad25eaaede16', 'High complexity', 'Service User is homeless or in temporary/unstable accommodation, or will be on release from prison. Service User has poor accommodation history, complex needs and limited skills to secure or sustain a tenancy.'),

        -- Education, Training and Employment (ETE) Service Category:
        ('0d6a7e24-2c61-4ca7-ac09-ec6f754dc6e5', 'ca374ac3-84eb-4b91-bea7-9005398f426f', 'Low complexity', 'Service User has satisfactory basic numeracy & literacy skills. The Service User has previously been employed though there may be gaps with periods of inactivity due to redundancy/periods of imprisonment. There has been no critical development need to find a new job in their previous field of competence. The Service User values benefits of working but needs guidance to re-enter the workforce, change jobs or career path.'),
        ('ab17dc4a-3f93-4ae5-a70d-2905b86b256c', 'ca374ac3-84eb-4b91-bea7-9005398f426f', 'Medium complexity', 'Service User has gaps in basic numeracy and literacy skills. The Service User has no or limited working experience. The Service User has partially completed vocational training but requires support with building confidence and motivation to develop training and/or employability skills, and also require support and coaching to develop or enhance skills to obtain and sustain employment.'),
        ('439c6dab-0dd6-4eb9-8a4a-c69d3490e940', 'ca374ac3-84eb-4b91-bea7-9005398f426f', 'High complexity', 'Service User lacks basic literacy & numeracy skills and/or may have Learning Difficulties and/or Learning Disabilities. The Service User has no or limited working experience and/or have no qualifications or current qualifications and/or may have many barriers and restrictions to employment due to the nature of their offences (e.g. sex offender or violence). The Service User requires significant support and coaching to build motivation, confidence and basic skills to enter employment / training.'),

        -- Finance, Benefits and Debt (FBD) Service Category:
        ('178ec337-0ec9-422c-b9da-ea969fdcf98a', '96a63c39-4371-4f17-a6ec-265755f0cf7b', 'Low complexity', 'Service User is not overly reliant on friends /family or others to supplement daily living expenses or regular outgoings. Service User''s circumstances may be currently leading to significant financial pressure but they are able to support themselves through legitimate means.'),
        ('d771ae5e-01d4-43b0-a941-99b2c0c52d29', '96a63c39-4371-4f17-a6ec-265755f0cf7b', 'Medium complexity', 'Service User may commit crimes ''on the side'' to supplement legal income or may rely on others for what they consider to be necessities. Service User may be unable to pay debts because of other ''demands''.'),
        ('65a682a7-9621-4dab-8040-08f3109321f8', '96a63c39-4371-4f17-a6ec-265755f0cf7b', 'High complexity', 'Service User income comes from the proceeds of crime, e.g. dealing drugs, robbery or stolen goods.  Service User relies on others for necessities and luxuries and servicing debts to illegitimate external sources. Service User may be unable to meet household and essential bills.'),

        -- Dependency and Recovery (D&R) Service Category:
        ('5392858e-3432-40cb-b277-4552e8ac4638', '76bcdb97-1dea-41c1-a4f8-899d88e5d679', 'Low complexity', 'Service User who is highly motivated and have had sustained period of abstinence. Service User has successfully engaged in a period of treatment but requires support to sustain recovery.'),
        ('f6a063e4-7daa-4cf6-9042-22476f8b5ed9', '76bcdb97-1dea-41c1-a4f8-899d88e5d679', 'Medium complexity', 'Service User who has had lapses/crises that may lead to relapse and/or is at a transition point, e.g. from prison into community. Service User has a moderate level of motivation but requires a high level of support.'),
        ('cf1fb9d3-5092-42dd-b8da-d9cedf96addc', '76bcdb97-1dea-41c1-a4f8-899d88e5d679', 'High complexity', 'Service User who is sentenced to Community Sentence where there is a Dual Diagnosis and substance misuse treatment. Service User does not meet the threshold for secondary provision and/or are deemed unsuitable following assessment for treatment as part of a Community Sentence Treatment Requirement.  However, Service User has identifiable substance misuse, alcohol misuse, prescription, gambling or other dependencies linked to re-offending. Service User has a history of poor engagement with treatment services and requires a high level of motivation and support to engage with treatment.'),

        -- Lifestyle and Associates Service Category:
        ('a8860894-2610-4070-aa66-72089417ceb2', 'b84f4eb7-4db0-477e-8c59-21027b3262c5', 'Low complexity', 'Service User lacks confidence to engage in community activities and/or spend a significant amount of time alone.  Service User recognises the value of strong pro-social support groups but is struggling to develop these fully. Service User has got one or more close friends not involved in criminal activity and/or spends limited time each week with non-offending peers or some affiliation to non-offending groups and activities, but does not have a central role. Service User may recognise that some lifestyle choices and associations have affected their behaviour and may trigger re-offending, such as illegal drug use, alcohol, gambling, peer choice, limited medium and long-term goals.'),
        ('707a0244-6bfe-4f0a-80d9-5e79498e81a8', 'b84f4eb7-4db0-477e-8c59-21027b3262c5', 'Medium complexity', 'Service User recognises the value of strong pro-social support groups but does not belong to any and shows limited interest in doing so. Service User spends the majority of their time alone or using social networking sites or web based sites but with limited face-to-face social interaction. Service User is aware of the value of positive attachments but does not have any at present and/or spends a significant amount of time with pro-criminal social groups. Service User engages in anti-social behaviours including (non-addiction) drug use, regular alcohol use, problematic gambling, poor behaviour that impact negatively on the wider community and/or displays impulsiveness in risk taking activities, e.g. putting themselves or others at risk of harm.'),
        ('005566a2-ca85-471c-9ac0-38f3aa749092', 'b84f4eb7-4db0-477e-8c59-21027b3262c5', 'High complexity', 'Service User has limited or no attachments/associations that are unrelated to offending behaviour. Service User does not belong to community groups or pro-social organised activities and does not place value on being part of them. Service User has no strong relationships outside of immediate family with people who don''t offend and/or spends the majority of their time alone using social networking sites or web based sites but with no face-to-face social interaction. Service User has strong links to county lines, gang affiliations, exposure to extremism, at risk of radicalisation, certain online offences.'),

        -- Family and Significant Others Service Category:
        ('ddc8ee4a-403e-47cc-9af1-815938429bbc', '9556a399-3529-4993-8030-41db2090555e', 'Low complexity', 'Service User has positive contact with some family or some significant others and may have positive support of family members. Service User has previously lost contact with family and recently renewed contacts but there remain some difficulties.'),
        ('8e409327-e3ab-4c91-9300-2f61a409789f', '9556a399-3529-4993-8030-41db2090555e', 'Medium complexity', 'Service User describes more difficulties in relationships with family and significant others or is in the process of resolving difficulties. Service User has a mix of good and difficult relationships with family and significant others.'),
        ('52ca5958-56c6-4ae3-99ca-86180265f717', '9556a399-3529-4993-8030-41db2090555e', 'High complexity', 'Service User has little or no contact with family and does not care about what family thinks feel or expects. Service User describes hostile, indifferent uncaring relationships with family and significant others. Service User''s relationship has recently ended or is likely to do so.'),

        -- Emotional Wellbeing Service Category
        ('cb6f1c1c-29d4-4d34-902e-3c89ee8428a0', '8221a81c-08b2-4262-9c1a-0ab3c82cec8c', 'Low complexity', 'Service User has worries or issues and feels unable to cope but is not socially isolated and interacts with others. Service User has no known psychological issues or history of depression and mental health.'),
        ('46c1ae33-f90b-4dfc-83f7-6eec49209084', '8221a81c-08b2-4262-9c1a-0ab3c82cec8c', 'Medium complexity', 'Service User has diagnosed documented psychological problems that are being managed well but requires support to maintain engagement. Service User has coping strategies but needs assistance. Service User shows signs of stress in meetings and requires support to effectively engage.'),
        ('64a1b7ba-305e-4bcc-b427-01b575ace941', '8221a81c-08b2-4262-9c1a-0ab3c82cec8c', 'High complexity', 'Service User has suffered psychological and mental health problems over a period of time which is documented, and needs significant level of support to engage with service provision. Service User is socially isolated and struggles with numerous aspects of daily life.'),

        -- Social Inclusion Service Category
        ('85aa5a57-62d3-4b9d-9642-248e7be4bebc', 'c036826e-f077-49a5-8b33-601dca7ad479', 'Low complexity', '[up to 4 Sessions (pre-release virtual contact)] Service User has a low risk of reoffending. Service User has limited family support or engagement with community services and there may be barriers to achieving community integration.'),
        ('64eb3c83-c562-4a63-9182-68a3a7725463', 'c036826e-f077-49a5-8b33-601dca7ad479', 'Medium complexity', '[up to 8 sessions (Including up to 2 pre-release face-to-face contacts)] Service User has medium risk of reoffending.  Service User has limited family support or engagement with community services and there may be barriers to achieving community integration. Service User has additional vulnerabilities requiring support through release and may have a pattern of non-compliance, e.g. recalls or failure to attend appointments.'),
        ('f1eebd5e-4a0f-457e-b1a8-62e8c7de1afd', 'c036826e-f077-49a5-8b33-601dca7ad479', 'High complexity', '[up to 12 sessions (including up to 3 pre-release face-to-face contacts)] Service User has high risk of reoffending. Service User has limited family support, a lack of social networks or minimal engagement with community services and there may be barriers to achieving community integration. Service User has additional vulnerabilities requiring support throughout release with a pattern of non-compliance and a high likelihood of non-compliance in early weeks of release, e.g. recalls or failure to attend appointments.');
