package uk.gov.justice.digital.hmpps.hmppsinterventionsservice.reporting.serviceprovider.performance

import java.time.OffsetDateTime
import java.util.UUID

data class PerformanceReportData(
  val referralReference: String,
  val referralId: UUID,
  val contractReference: String,
  val organisationId: String,
  val currentAssigneeEmail: String?,
  val serviceUserCRN: String,
  val dateReferralReceived: OffsetDateTime,
  val firstActionPlanSubmittedAt: OffsetDateTime?,
  val firstActionPlanApprovedAt: OffsetDateTime?,
  val firstSessionAttendedAt: OffsetDateTime?,
  val numberOfOutcomes: Int?,
  val achievementScore: Float?,
  val numberOfSessions: Int?,
  val numberOfSessionsAttended: Int?,
  val endRequestedAt: OffsetDateTime?,
  val endRequestedReason: String?,
  val eosrSubmittedAt: OffsetDateTime?,
  val concludedAt: OffsetDateTime?,
  val referralEndState: String?,
  val dateSupplierAssessmentBooked: OffsetDateTime?,
  val dateSupplierAssessmentFirstScheduledFor: OffsetDateTime?,
  val dateSupplierAssessmentFirstNotAttended: OffsetDateTime?,
  val dateSupplierAssessmentFirstAttended: OffsetDateTime?,
  val supplierAssessmentAttendedOnTime: Boolean?,
) {
  companion object {
    // it would be neater to use reflection to get the fields, but we cannot guarantee the order
    val fields = listOf(
      "referralReference",
      "referralId",
      "contractReference",
      "organisationId",
      "currentAssigneeEmail",
      "serviceUserCRN",
      "dateReferralReceived",
      "firstActionPlanSubmittedAt",
      "firstActionPlanApprovedAt",
      "firstSessionAttendedAt",
      "numberOfOutcomes",
      "achievementScore",
      "numberOfSessions",
      "numberOfSessionsAttended",
      "endRequestedAt",
      "endRequestedReason",
      "eosrSubmittedAt",
      "concludedAt",
      "referralEndState",
      "dateSupplierAssessmentBooked",
      "dateSupplierAssessmentFirstScheduledFor",
      "dateSupplierAssessmentFirstNotAttended",
      "dateSupplierAssessmentFirstAttended",
      "supplierAssessmentAttendedOnTime",
    )
    val headers = listOf(
      "referral_ref",
      "referral_id",
      "contract_ref",
      "organisation_id",
      "caseworker_id",
      "service_user_crn",
      "date_referral_received",
      "date_first_action_plan_submitted",
      "date_of_first_action_plan_approval",
      "date_of_first_attended_session",
      "outcomes_to_be_achieved_count",
      "outcomes_achieved",
      "count_of_sessions_expected",
      "count_of_sessions_attended",
      "end_requested_by_pp_at",
      "end_requested_by_pp_reason",
      "date_eosr_submitted",
      "concluded_at",
      "referral_end_state",
      "date_saa_booked",
      "date_saa_first_scheduled_for",
      "date_saa_first_not_attended",
      "date_saa_first_attended",
      "saa_attended_on_time",
    )
  }
}
