{{- if .Values.env_details.production_env -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-refresh-script
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e

    echo "${DB_HOST}:5432:${DB_NAME}:${DB_USER}:${DB_PASS}" > ~/.pgpass
    echo "${DB_HOST_PREPROD}:5432:${DB_NAME_PREPROD}:${DB_USER_PREPROD}:${DB_PASS_PREPROD}" >> ~/.pgpass
    chmod 0600 ~/.pgpass

    set -x
    pg_dump --host="$DB_HOST" --username="$DB_USER" --format=custom --no-privileges --verbose --file=/tmp/db.dump "$DB_NAME"
    pg_restore --host="$DB_HOST_PREPROD" --username="$DB_USER_PREPROD" --clean --no-owner --verbose --dbname="$DB_NAME_PREPROD" /tmp/db.dump

    rm -v /tmp/db.dump ~/.pgpass
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-refresh-job
spec:
  schedule: "0 8 * * 0"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 1200
      template:
        spec:
          securityContext:
            runAsUser: 999
          containers:
            - name: dbrefresh
              image: "postgres:10"
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: db-refresh-script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              env:
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: database_name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: database_username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: database_password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: rds_instance_address
                - name: DB_NAME_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-preprod
                      key: database_name
                - name: DB_USER_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-preprod
                      key: database_username
                - name: DB_PASS_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-preprod
                      key: database_password
                - name: DB_HOST_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-preprod
                      key: rds_instance_address
          restartPolicy: "Never"
          volumes:
            - name: db-refresh-script
              configMap:
                name: db-refresh-script
                defaultMode: 0755
{{- end }}
