{{- if .Values.env_details.production_env -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kpi-scripts
data:
{{ (.Files.Glob "reports/*.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "reports/team_kpi*.sql").AsConfig | indent 2 }}

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: team-kpis
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          volumes:
          - name: kpi-scripts
            configMap:
              name: kpi-scripts
              defaultMode: 0755
          containers:
          - name: data-extractor-reporting
            image: ministryofjustice/data-engineering-data-extractor:v1
            imagePullPolicy: Always
            args:
              - |
                psql -v ON_ERROR_STOP=1 --tuples-only --expanded --file=/reports/team_kpi_report.sql > 'export/team_kpi_report' \
                  && /scripts/send_to_slack.sh 'export/team_kpi_report'
              - |
                psql -v ON_ERROR_STOP=1 --pset="footer=off" --file=/reports/team_kpi_details_report.sql > 'export/team_kpi_details_report' \
                  && /scripts/send_to_slack.sh 'export/team_kpi_details_report'
            volumeMounts:
            - name: kpi-scripts
              mountPath: /reports/team_kpi_report.sql
              readOnly: true
              subPath: team_kpi_report.sql
            - name: kpi-scripts
              mountPath: /reports/team_kpi_details_report.sql
              readOnly: true
              subPath: team_kpi_details_report.sql
            - name: kpi-scripts
              mountPath: /scripts/send_to_slack.sh
              readOnly: true
              subPath: send_to_slack.sh
            env:
              - name: ENVIRONMENT
                value: {{ .Values.env.SENTRY_ENVIRONMENT | quote }}
              - name: SLACK_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: statistician-slack
                    key: webhook-url
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: rds_instance_address
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_name
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_password
{{- end }}
