apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-extractor
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
          - name: data-extractor
            image: ministryofjustice/data-engineering-data-extractor:develop
            command: ["sh", "-c", "extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh"]
            env:
              - name: LOCAL_EXPORT_DESTINATION
                value: export
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: rds_instance_address
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_name
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: database_password
              - name: S3_DESTINATION
                valueFrom:
                  secretKeyRef:
                    name: analytical-platform-reporting-s3-bucket
                    key: destination_bucket
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: analytical-platform-reporting-s3-bucket
                    key: access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: analytical-platform-reporting-s3-bucket
                    key: secret_access_key
              - name: AWS_DEFAULT_REGION
                value: eu-west-2
